version: '3.8'

services:
  app:
    image: whichme_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: WhichMe_Backend
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/whichme?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: whichme9764
    volumes:
      - ./src:/app/src  # 호스트의 소스 디렉토리를 컨테이너와 연결
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: whichme9764
      MYSQL_DATABASE: whichme
    ports:
      - "3306:3306"
